### ISSUE TITLE
Doesn't work with IE11 and ES6 scripts

### ISSUE THREAD

**Issue by Yegorich555** [ElemeFE/obsolete-webpack-plugin#10]
## Environment

- Plugin Version: 0.5.6
- Webpack Version: 4.35.3
- OS Version: Windows 10 x64
- Node Version: 10.11.0
- NPM Version: 6.7.0
- Browser Version: IE 11

## Current Behavior

The browser stucks with error in main scripts (since ES6 incompatibility) and there is no any actions from obsolete.js

## Expected Behavior

The browser should show the default obsolete-message

### How to reproduce

1) Create any project with ```webpack 4``` and ```obsolete-webpack-plugin```
2) Add to ```.browserslistrc``` with 'excluding of IE11' and any incompatible ES6 browsers (you can set the only ```last 5 Chrome version``` string)
3) Add any ES6 script to index.js
4) Compile and look into results in IE11 - browser finds the error in main.js and there are no actions from obsolete.js

It may be issue IE11, but how can it be resolved?

**Comment by chikara-chan** [comment]
https://github.com/ElemeFE/obsolete-webpack-plugin#configuration-book

Just set `promptOnNonTargetBrowser ` to `true`.

**Comment by Yegorich555** [comment]
Yep. I can't imagine that this property is false by default.... Thanks a lot.
