### ISSUE TITLE
Cannot work below ie10 

### ISSUE THREAD

**Issue by zhaosiwen1949** [ElemeFE/obsolete-webpack-plugin#4]
## Environment

IE 10, IE 9 and below

## Current Behavior

Cannot work, and console the error ---- "Object does not support the "getElementById" property or method"

## Expected Behavior

Can work

## Detailed Description

 I find this
```
 bindEvents(fragment) {
    const close = fragment.getElementById('obsoleteClose');

    if (!close) {
      return;
    }
```
In line 49, alert.js
But fragment.getElementById can't work under IE 10, [https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment)
Can it be replaced by fragment.querySelector, thank u~~~

**Comment by chikara-chan** [comment]
Fixed in v0.5.4.
