### ISSUE TITLE
Incompatibility with vue-cli modern mode

### ISSUE THREAD

**Issue by Djaler** [ElemeFE/obsolete-webpack-plugin#7]
## Environment

- Plugin Version: 0.5.5
- Webpack Version: 4.28.1
- OS Version: Debian 9
- Node Version: 10
- NPM Version: 6
- @vue/cli-service Version: 3.3.0

## Current Behavior

`Uncaught TypeError: Cannot set property 'Obsolete' of undefined` when opened in modern browser with modules support

## Expected Behavior

Work fine in both modern and legacy browsers

## Detailed Description

Here are documentation about modern mode - https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode

**Comment by chikara-chan** [comment]
Can you reproduce again?
Or more detailed description, which browser, browserslist config, build result.

**Comment by Djaler** [comment]
I create a sample project for you - https://github.com/Djaler/obsolete-webpack-plugin-vue-cli-modern-mode-bug-sample

Steps to reproduce:
1. `npm install`
2. `npm run build`
3. Run project using any HTTP-serve. For example, serve. 
```
npm install -g serve
serve -s dist
```
4. Open in modern browser (latest Chrome, for example)
5. You will see error in console

This happens because in modern mode vue cli produces two versions for each script - for modern and legacy browsers.
Modern browser will load `<script type=module>`:
`<script type=module src=/js/obsolete.5561cfbb.js></script>`
and will not load `<script nomodule`:
`<script src=/js/obsolete-legacy.5561cfbb.js nomodule></script>`.
And legacy browser will do the opposite.

The problem is that your script is not designed to run as an ES-module.

**Comment by Djaler** [comment]
I make a simple plugin and run it after `ObsoleteWebpackPlugin` as a temporary workaround, but this is ugly.

<details>
 <summary>Code</summary>
<pre>
class ObsoleteBrowserModernModeFixPlugin {
    constructor(obsoleteBrowserChunkName) {
        this.chunkName = obsoleteBrowserChunkName;
    }

    apply(compiler) {
        const ID = 'obsolete-browser-modern-mode-fix';

        compiler.hooks.compilation.tap(ID, (compilation) => {
            compilation.hooks.htmlWebpackPluginAlterAssetTags.tap(ID, (data) => {
                _.remove(data.head, tag => this.isMatchedModulePreloadLink(tag));

                _.remove(data.body, tag => this.isMatchedNoModuleLegacyScript(tag));

                data.body.filter(tag => this.isMatchedModuleScript(tag))
                    .forEach(tag => delete tag.attributes.type);
            });
        });

        compiler.hooks.emit.tap(ID, (compilation) => {
            Object.keys(compilation.assets)
                .forEach((assetName) => {
                    if (assetName.includes(`${this.chunkName}-legacy`)) {
                        delete compilation.assets[assetName];
                    }
                });
        });
    }

    isMatchedModulePreloadLink(tag) {
        return (tag.tagName === 'link' && tag.attributes && tag.attributes.href.includes(this.chunkName)
            && tag.attributes.rel === 'modulepreload');
    }

    isMatchedNoModuleLegacyScript(tag) {
        return (tag.tagName === 'script' && tag.attributes && tag.attributes.src.includes(`${this.chunkName}-legacy`)
            && tag.attributes.nomodule !== undefined);
    }

    isMatchedModuleScript(tag) {
        return (tag.tagName === 'script' && tag.attributes && tag.attributes.src.includes(this.chunkName)
            && tag.attributes.type === 'module');
    }
}
</pre>
</details>

**Comment by chikara-chan** [comment]
Fixed in v0.5.6.

**Comment by Djaler** [comment]
Awesome, thanks!
